# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'siva921'
    scannerMode: 'MSBuild'
    projectKey: 'pipelines-dotnet-core'
    projectName: 'pipelines-dotnet-core'
- task: Ant@1
  inputs:
    buildFile: 'build.xml'
    options: 
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    codeCoverageToolOptions: 'Cobertura'
    codeCoverageClassFilesDirectories: '.'
    codeCoverageFailIfEmpty: true
    javaHomeOption: 'JDKVersion'


